[deployment] finding error in ndk installation
Signed-off-by: electricherd <electricherd@users.noreply.github.com>

diff --git a/.github/workflows/ci_android.yml b/.github/workflows/ci_android.yml
--- a/.github/workflows/ci_android.yml
+++ b/.github/workflows/ci_android.yml
@@ -141,23 +141,17 @@ jobs:
         shell: bash
         run: cargo install cargo-ndk --version 1.0.0
 
-      # helper to find problems
-      - name: find clang android compiler
-        continue-on-error: true
-        shell: bash
-        run: find /home/runner -name x86_64-linux-android28-clang || echo "not found"
-
       # 2nd helper to find problems
       - name: find more
         continue-on-error: true
         shell: bash
         run: ls $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/ || echo "dir not found"
 
-      # 3rd helper to env-vars
-      - name: find target / host
+      # 3rd helper to ndk helper files
+      - name: find ndk files
         continue-on-error: true
         shell: bash
-        run: echo "$CARGO_BUILD_TARGET" || echo "var not found"
+        run: ls -R $ANDROID_NDK_HOME/toolchains || echo "this dir not found"
 
       # ############### Release/Debug build dependent
       - name: Run cargo make android - Debug
